### ISSUE TITLE
Provide a link to view/interact with your work

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [devmikev/warehouse_assessment#1]
It would be helpful to link to a http://jsfiddle.net/ or http://plnkr.co/edit/ showing the html and javascript up and running.

**Comment by ImaginaryDevelopment** [comment]
I wanted to see what this project looked like so I made a plunk http://next.plnkr.co/edit/CrUEOArpjBZRFVtb

**Comment by devmikev** [comment]
https://devmikev.github.io/warehouse_assessment/
